name: Run Unit Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  BASEURL: ${{ secrets.BASE_URL }}
  CLIENTID: ${{ secrets.CLIENTID }}

jobs:
  ci:
    name: Run Unit Test
    runs-on: ubuntu-latest
    
    steps: 
     - uses: actions/checkout@v2
     - name: set up JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
     
     - name: Unit Test
       run: bash ./gradlew assembleDebug --stacktrace
